apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    chart: cert-manager
    targetRevision: 1.18.2
    repoURL: https://charts.jetstack.io
    helm:
      releaseName: cert-manager
      namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
