apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager    # Best practice to run cert-manager in its own namespace
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    helm:
      releaseName: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5              # Number of sync retries
      backoff:
        duration: 5s        # Initial backoff duration
        factor: 2           # Factor to multiply duration after each failure
        maxDuration: 3m     # Maximum backoff duration
