#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: cert-manager
#  namespace: argocd
#spec:
#  project: default
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: cert-manager
#  source:
#    chart: cert-manager
#    repoURL: https://charts.jetstack.io
#    targetRevision: v1.18.2
#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
