apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
spec:
  project: default
  source:
    chart: k8ssandra
    repoURL: https://helm.k8ssandra.io/stable
    targetRevision: 1.5.2
    helm:
      releaseName: cassandra
      namespace: k8ssandra
      values: | 
        cassandra:
          auth:
            enabled: true
          clusterName: mixed-workload
          datacenters:
            - name: dc1
              size: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: k8ssandra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

