apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: cassandra-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  class: com.datastax.oss.kafka.sink.CassandraSinkConnector
  tasksMax: 1
  config:
    topics: spin.history.slot_game.spins_by_user
    contactPoints: demo-dc1-contact-points-service.k8ssandra.svc.cluster.local
    loadBalancing.localDc: dc1
    keyspace: slot_game
    table: spin_history
    topic.spin.history.slot_game.spins_by_user.mapping: "username=value.username, spin_id=value.spinId, timestamp=value.timestamp, bet_amount=value.betAmount, win_amount=value.winAmount, result=value.result"
    topic.spin.history.slot_game.spins_by_user.consistencyLevel: "LOCAL_QUORUM"
    auth.username: demo-superuser
    auth.password: 6J1xnqV93RkEp4Qunvf4