apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/vdksystem/global-cluster.git
      revision: HEAD
      directories:
      - path: gitops/apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default

      destination:
        server: https://kubernetes.default.svc

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
