apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/vdksystem/global-cluster.git
    targetRevision: HEAD
    path: gitops/manifests/cassandra
  destination:
    server: https://kubernetes.default.svc
    namespace: k8ssandra
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true