---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-infra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: k8s-infra
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  targetNamespace: signoz
  interval: 1m0s
  install:
    createNamespace: true
  dependsOn:
    - name: signoz
  values:
    global:
      cloud: aws
      clusterName: production
      deploymentEnvironment: PRD
    otelCollectorEndpoint: signoz-signoz-otel-collector.signoz.svc.cluster.local:4317
    otelInsecure: true
    presets:
      otlpExporter:
        enabled: true
      loggingExporter:
        enabled: false
      resourceDetection:
        detectors:
          - eks
          - system

