---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: signoz
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  targetNamespace: signoz
  interval: 1m0s
  install:
    createNamespace: true
