---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: signoz
spec:
  chart: signoz
  sourceRef:
    kind: HelmRepository
    name: signoz
    namespace: flux-system
  interval: 1m0s
