apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - kafka-single-node.yaml
  - kafka-connect.yaml
  - cassandra-connector.yaml
  - topics/spin_history.yaml
